### ISSUE TITLE
Weird license?

### ISSUE THREAD

**Issue by jeena** [Pelagicore/QmlAssetExporter#1]
The license here https://github.com/Pelagicore/QmlAssetExporter/blob/master/LICENSE.CC-BY-NC-SA will prevent the designers or our customers to use it, won't it? Or are they supposed to buy a license?

Or is that just a copy&paste bug because it somehow mentiones Neptune IVI UI Assets?

**Comment by jeremiah** [comment]
I believe the license just refers to assets and not to code here. In which case, it should be fine. I'll close this.

**Comment by Gagi2k** [comment]
True, but that means the general license is missing and basically it means that nobody can use it currently as AFAIK no license == "most restricted"
